spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/credit_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yml
    enabled: true

server:
  port: 8083

