spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/credit_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.yml
    enabled: true

server:
  port: 8083

ms1:
  url: "http://localhost:8081/clients/"

credit:
  limit: 2000000

